#!/usr/bin/env python

import sys
print ">>> start"
assert(len(sys.argv) > 2)

from DAS18.CommonTools.paralell import *
print ">>> Parallel(" + sys.argv[1] + ", " + sys.argv[2] + ", ...)"
parallel(sys.argv[1], sys.argv[2], *sys.argv[3:])

